### ISSUE TITLE
Allow migrations of discussions

### ISSUE THREAD

**Issue by jozefizso** [Microsoft/CodePlexWorkItemMigrator#1]
CodePlex does not have API access to list of discussions and their details right now. CodePlex should be upgraded to allow API access to this data.

This migration tool should be improved by adding support to migrate discussions as well.

**Comment by infin8x** [comment]
Thanks for the feedback. This is under consideration but I don't have any firm plans to share at this time.

**Comment by jozefizso** [comment]
Hi @alexmullans, do you have any updates about this? Migrating discussions content is crucial for projects migration away from CodePlex.

**Comment by infin8x** [comment]
@jozefizso we won't be providing an API or updating the migration tool, but when the archive site is online, you'll be able to download a complete set of discussions. From there, you can create your own scripts/tooling to import your discussions where they make sense for your project.
